### ISSUE TITLE
Git status truncates branch names

### ISSUE THREAD

**Issue by milesj** [mroth/scmpuff#12]
Just noticed that `gs` truncates branch names that are based on versions. For example:

```
[21:25:11] Miles:toolkit > gs
# On branch: 3  |  No changes (working directory clean)
[21:25:15] Miles:toolkit > git status
On branch 3.0
Your branch is up-to-date with 'origin/3.0'.
nothing to commit, working directory clean
```

**Comment by mroth** [comment]
Huh!  Something must be messed up with the pattern matching.  I'll look into this.

**Comment by mroth** [comment]
@milesj could you please do a `git status -z -b` in the branch of question and let me know what the output looks like?

**Comment by milesj** [comment]
Sure, here you are.

```
[19:28:23] Miles:toolkit > git status -b -z
## 3.0...origin/3.0 [ahead 1]
```

**Comment by mroth** [comment]
Okay, reproduced and added a failing test for this in ee03e30.

Will try to take a look at this soon.  (If someone wants to take a stab at it before me, the offending code is almost certainly in https://github.com/mroth/scmpuff/blame/truncated-branch-names/commands/status/process.go#L69-L77 )

**Comment by milesj** [comment]
Awesome thanks!
