### ISSUE TITLE
Seems wrong color in scmpuff_status

### ISSUE THREAD

**Issue by bestswifter** [mroth/scmpuff#32]
In normal git status, files which haven't been staged are shown in red color while staged files are shown in green color.

However, in the output of scmpuff_status, files which haven't been staged are shown in green and the staged files are shown in yellow which I think is not intuitional. 

Is this a bug or feature?

**Comment by mroth** [comment]
The colors (and the rest of the UI) were originally picked to be an exact
match for scm_breeze.  In the future, it could be possible to add a
customization option.

**Comment by killerkiara** [comment]
Is there in the meantime any update on this feature @mroth ? Thank you :)

**Comment by mroth** [comment]
@killerkiara if you want to take a stab at a PR towards an architecture for this I can review it.

Basically the colors are defined here:
https://github.com/mroth/scmpuff/blob/master/commands/status/constants.go

I think what I'd probably do is have the program check for the presence of environment variables at initialization, e.g. `$SCMPUFF_COLOR_RST` etc.  I think there's a valid open question as to how this would interact with #28 for cross platform support however, and so they should be reconciled.
