### ISSUE TITLE
Doesn't work properly when git just initialized

### ISSUE THREAD

**Issue by zommerfelds** [mroth/scmpuff#36]
```
mkdir tmp
cd tmp
git init
touch hello
git add hello
```

Prints
```
2018/03/11 01:19:58 Failed to parse branch name for output: [## No commits yet on master]
```
Same for `gs`. `git status` works

**Comment by mroth** [comment]
Ah yes.  Should be relatively simple to address by adding in `ExtractBranch` and adding a test case, if someone wants to take this on as a good introductory PR for the project!
