### ISSUE TITLE
bindata issues after generating new files

### ISSUE THREAD

**Issue by zommerfelds** [mroth/scmpuff#38]
Hi, this is probably more of a question than a bug report. How do I run the cucumber tests?

If I run `bundle exec cucumber` I get a few errors:
https://gist.github.com/zommerfelds/63fdbeb161fc6af3ce9224e39a16a2dc

My system is Arch Linux.

I was hoping to potentially help out getting this to work on Windows, but want to scope out what the current challenge is running the integration tests on Appveyor.

**Comment by mroth** [comment]
In general, most of the build tasks are handled via the `Rakefile`, so once you've installed the bundle deps (which it looks like you did already), you should be able to do `rake -T` to see available tasks, and `rake features` to run the integration tests. It's probably worth looking at the `Rakefile` itself to see what's going on, it's pretty minimal and decently documented.

Interestingly though, it looks like this error stems from:
`panic: Could not find bindata asset file: data/status_shortcuts.sh`

I use `go-bindata` as part of the build process to embed the shell scripts files into the binary. But that's only done in development, and the resulting file `commands/inits/bindata.go` is checked into git, so if you cloned the repo you should have it already and therefore it doesn't make much sense to me why that error is cropping up.

Does it only happen when running tests? Or if you compile the binary locally and run something like `scmpuff init -s`does it also panic with the same message?

**Comment by zommerfelds** [comment]
Sorry to get back so late!
Yes, you are right, the compiled binary also gave me the same message:
```
$ bin/scmpuff init -s
panic: Could not find bindata asset file: data/status_shortcuts.sh
```

I don't know entirely what the purpose of `binddata.go` is, but I my system is generating a different version of that file, which is breaking the program. If I check the original file out and run `script/build` directly (without the generate task), then it works.

Here is my new `binddata.go` file for reference: https://gist.github.com/zommerfelds/63fdbeb161fc6af3ce9224e39a16a2dc#file-binddata-go

The cucumber tests are passing for me now if I don't regenerate the files.

**Comment by mroth** [comment]
Interesting.  I'm going to leave this issue open for now, since it's possible there may be better ways to approach the bindata stuff now a few years later, so I will use this issue as a reminder to look into alternatives.

**Comment by mroth** [comment]
See also: 
https://github.com/jteeuwen/go-bindata/issues/5

It may be worth looking into a more supported contemporary alternative for bindata.
