### ISSUE TITLE
Add example to readme for reusing numbered variables?

### ISSUE THREAD

**Issue by themrmax** [mroth/scmpuff#41]
How would you recommend reusing the numbered variables e.g. for opening files for editing .... would I have to do something like this:

```bash
alias v1="vim $e1"
alias v2="vim $e2"
alias v3="vim $e3"
# etc
```

or is there a way to make `vim 1` automatically expand into `vim $e1`

**Comment by mroth** [comment]
You can see some usage in the git wrapper shell script:
https://github.com/mroth/scmpuff/blob/master/commands/inits/data/git_wrapper.sh

I'm guessing for this, you might want to make a vim shell wrapper with something like:
```bash
eval "$(scmpuff expand -- "$EDITOR" "$@")"
```

Play around with the `scmpuff expand` command to get some ideas.  It basically takes a string and tries to expand any numbers into the corresponding file path if an env var is set. In the example above, the `--` separates the flags from what gets passed to the command.  E.g.

`scmpuff expand -- vim foo.txt` will output `vim foo.txt`, but `scmpuff expand -- vim 2 3` would output the string `vim filename1.c filename2.h`.  In a bash/zsh shell script, you'd then want to `eval` that to execute it as a command.

**Comment by mroth** [comment]
Closing for now since it appears resolved, but if you want to author a guide for the README or some such, I'll gladly review a PR.
