### ISSUE TITLE
Puff breaks if the merge has a lot of files

### ISSUE THREAD

**Issue by vansivallab** [mroth/scmpuff#42]
to reproduce:
```
git merge master # into an old branch
git status
```

I got the error: `git:3: argument list too long: scm puff`

version 0.2.1 on Mac

**Comment by mroth** [comment]
How many files we talking about here? I'm having trouble reproducing even with hundreds of files. 

(That error message makes me suspicious the problem is somehow happening in your shell alises somehow, due to the strange spacing between `scm` and `puff` -- our binary is called `scmpuff`..._)

**Comment by vansivallab** [comment]
Hmm I'm also having a hard time recreating the error. I can re-open this issue if it happens again.

**Comment by alexandreblin** [comment]
I've had the same problem happen with ~5000 files (adding `Pods` folder in an iOS project haha)

**Comment by natsumi** [comment]
same issue happening.. ~8000 files

**Comment by zerovox** [comment]
I get this quite a lot working in a big repo, any anything over 999 wont be cleaned up by `scmpuff_clear_vars`:
https://github.com/mroth/scmpuff/blob/ab65b2aa3fbdb9fcbc6a9b836065d4c38a829a41/commands/inits/data/status_shortcuts.sh#L45

As an alternative to the above,`typeset +x -m 'e*'` will clear out all the scmpuff variables (assuming you have no other env vars starting with an `e`). It would be good to add a limit to prevent creating more than 1000 or so env vars.
