### ISSUE TITLE
doesn't work with git alias

### ISSUE THREAD

**Issue by manuelmeurer** [mroth/scmpuff#47]
Hey, thanks for this great project! 😄 	
I have a few [git aliases](https://github.com/krautcomputing/dotfiles/blob/master/gitconfig#L5) defined and scmpuff doesn't work when I use them, e.g. `a` for `add`:

```
$ gs
# On branch: master  |  [*] => $e*
#
➤ Untracked files
#
#      untracked:  [1] my_file.txt
#

$ g a 1
fatal: pathspec '1' did not match any files

$ g add 1
# On branch: master  |  [*] => $e*
#
➤ Changes to be committed
#
#       new file:  [1] my_file.txt
#
```

What could be the problem?

**Comment by eskerber** [comment]
Oddly enough I came here looking to see if this was an issue and saw it was written today 😄 

I also experience this, and thought the lack of other issues meant I was holding scmpuff wrong.

**Comment by mroth** [comment]
So, essentially how scmpuff integrates with a user's shell is it wraps the git command, and rewrites certain patterns to expand variables prior to them getting to git.

The relevant part of the actual bash/zsh wrapper used is currently:
```shell
function git() {
  case $1 in
    commit|blame|log|rebase|merge)
      eval "$(scmpuff expand -- "$SCMPUFF_GIT_CMD" "$@")";;
    checkout|diff|rm|reset)
      eval "$(scmpuff expand --relative -- "$SCMPUFF_GIT_CMD" "$@")";;
    add)
      eval "$(scmpuff expand -- "$SCMPUFF_GIT_CMD" "$@")"
      scmpuff_status;;
    *)
      "$SCMPUFF_GIT_CMD" "$@";;
  esac
}
```

Now, if you are using say, a standard shell alias (`alias ga='git add'`), your shell will expand it before it gets executed, so when it hits the scmpuff wrapper function, we can pattern match against it.

However, in this case, where you are using built-in git aliases, those are not expanded -- rather, git processes them internally, so we have no opportunity to see the unaliased command before it gets to the git binary.  This is more a shell/git issue than a scmpuff one -- there's not a way around it that I'm aware of (short of forking git and making our own version).  For this reason, I recommend only using built in git aliases for things like adding default arguments or creating new commands, but not shortcuts -- for that, use of a shell alias is going to be more reliable and compatible with shell integrations.

Does that make sense?

**Comment by mroth** [comment]
As a further example, in my personal git configuration, here is the sort of thing I use git aliases for:

(From .gitconfig)
```
[alias]
	amend = commit --amend -C HEAD
	smash = rebase --autosquash --committer-date-is-author-date
	log = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
```

In contrast, I uses shell aliases like such:
```shell
$ alias | grep git 
ga='git add'
gco='git checkout'
gd='git diff'
gl='git log'
grs='git reset'
```

Hope this is helpful!

**Comment by eskerber** [comment]
@mroth it is! Seems like this can be closed out and used for reference.
