### ISSUE TITLE
Add scmpuff to oh-my-zsh plugins

### ISSUE THREAD

**Issue by pmastela** [mroth/scmpuff#73]
Make enabling scmpuff as simple as adding `scmpuff` to the list of plugins in one's `.zshrc`. Side benefit for the project would be that it would be listed in [oh-my-zsh plugins](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins) thus likely driving higher adoption.

**Comment by mroth** [comment]
scmpuff is a binary (and thus OS/platform specific), not a zsh script, so I don't believe that would work.  If there is an easy way to do so, please open a PR and let me know.
